@extends('layouts.admin')

@section('title', 'Monitoring Absensi')
@section('page_title', 'Real-time Monitoring Absensi')

@section('content')
<div class="container-fluid">
    <div class="row">
        <!-- Calendar Column -->
        <div class="col-md-3">
            <div class="card shadow-sm border-0 mb-4 sticky-top calendar-sidebar" style="top: 80px; z-index: 10;">
                <div class="card-header bg-white py-3 border-0">
                    <h3 class="card-title mb-0">
                        <i class="fas fa-calendar-alt mr-2 text-primary"></i> Kalender Presensi
                    </h3>
                </div>
                <div class="card-body pt-0">
                    <!-- Modern Custom Calendar -->
                    <div class="custom-calendar mb-4" id="customCalendar">
                        <div class="calendar-header d-flex align-items-center justify-content-between mb-3">
                            <button type="button" class="btn btn-icon-small" id="prevMonth"><i class="fas fa-chevron-left fa-xs"></i></button>
                            <h6 class="mb-0 font-weight-bold" id="monthDisplay" style="font-size: 0.85rem;">Januari 2026</h6>
                            <button type="button" class="btn btn-icon-small" id="nextMonth"><i class="fas fa-chevron-right fa-xs"></i></button>
                        </div>
                        <div class="calendar-weekdays mb-2">
                            <span>M</span><span>S</span><span>S</span><span>R</span><span>K</span><span>J</span><span>S</span>
                        </div>
                        <div class="calendar-days" id="calendarDays">
                            <!-- Days will be generated by JS -->
                        </div>
                    </div>
                    
                    <div class="stats-container p-3 rounded-xl bg-light border-0">
                        <h6 class="text-muted font-weight-bold small text-uppercase mb-3 letter-spacing-1">Statistik Harian</h6>
                        @php
                            $totalPresent = $employees->filter(fn($e) => optional($e->attendances->first())->status === 'Present')->count();
                            $totalLate = $employees->filter(fn($e) => optional($e->attendances->first())->status === 'Late')->count();
                            $totalPermission = $employees->filter(fn($e) => optional($e->attendances->first())->status === 'Permission')->count();
                            $totalAlpha = $employees->filter(fn($e) => optional($e->attendances->first())->status === 'Alpha')->count();
                            $totalEmployees = $employees->count();
                        @endphp
                        
                        <div class="stat-row d-flex justify-content-between align-items-center mb-2 p-2 rounded transition-all">
                            <span class="small text-dark font-weight-600"><i class="fas fa-check-circle text-success mr-2"></i>Hadir</span>
                            <span class="badge badge-soft-success font-weight-bold">{{ $totalPresent }}</span>
                        </div>
                        <div class="stat-row d-flex justify-content-between align-items-center mb-2 p-2 rounded transition-all">
                            <span class="small text-dark font-weight-600"><i class="fas fa-clock text-warning mr-2"></i>Terlambat</span>
                            <span class="badge badge-soft-warning font-weight-bold">{{ $totalLate }}</span>
                        </div>
                        <div class="stat-row d-flex justify-content-between align-items-center mb-2 p-2 rounded transition-all">
                            <span class="small text-dark font-weight-600"><i class="fas fa-envelope-open-text text-info mr-2"></i>Izin</span>
                            <span class="badge badge-soft-info font-weight-bold">{{ $totalPermission }}</span>
                        </div>
                        <div class="stat-row d-flex justify-content-between align-items-center p-2 rounded transition-all">
                            <span class="small text-dark font-weight-600"><i class="fas fa-user-times text-secondary mr-2"></i>N/A</span>
                            <span class="badge badge-soft-secondary font-weight-bold">{{ $totalEmployees - ($totalPresent + $totalLate + $totalPermission + $totalAlpha) }}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Monitoring Column -->
        <div class="col-md-9">
            <div class="card shadow-sm border-0 overflow-hidden main-card">
                <div class="card-header bg-white py-3 d-flex align-items-center justify-content-between">
                    <h3 class="card-title mb-0">
                        <i class="fas fa-desktop mr-2 text-primary"></i> Status Kehadiran
                        <span class="text-muted small ml-2">{{ \Carbon\Carbon::parse($date)->translatedFormat('l, d F Y') }}</span>
                    </h3>
                    <div class="card-tools">
                        <a href="{{ route('attendance.index') }}" class="btn btn-primary btn-sm rounded-pill px-3 shadow-sm border-0">
                            <i class="fas fa-history mr-1"></i> Lihat Riwayat Seluruh Absensi
                        </a>
                    </div>
                </div>
                <div class="bg-primary" style="height: 3px; width: 100%;"></div>
                <div class="card-body p-0">
                    <div class="table-responsive">
                        <table class="table table-hover align-middle mb-0" id="monitoringTable">
                            <thead class="bg-light text-muted small text-uppercase">
                                <tr>
                                    <th class="text-center px-4" width="50">No</th>
                                    <th>Karyawan</th>
                                    <th class="text-center">Waktu Masuk</th>
                                    <th class="text-center">Waktu Keluar</th>
                                    <th class="text-center">Status</th>
                                    <th class="text-center px-4" width="120">Tindakan</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($employees as $employee)
                                    @php
                                        $att = $employee->attendances->first();
                                        $status = $att ? $att->status : '-';
                                        $timeIn = $att && $att->time_in ? \Carbon\Carbon::parse($att->time_in)->format('H:i') : '-';
                                        $timeOut = $att && $att->time_out ? \Carbon\Carbon::parse($att->time_out)->format('H:i') : '-';
                                        
                                        switch ($status) {
                                            case 'Present':
                                                $statusConfig = ['label' => 'HADIR', 'class' => 'badge-soft-success'];
                                                break;
                                            case 'Late':
                                                $statusConfig = ['label' => 'TERLAMBAT', 'class' => 'badge-soft-warning'];
                                                break;
                                            case 'Permission':
                                                $statusConfig = ['label' => 'IZIN/SAKIT', 'class' => 'badge-soft-info'];
                                                break;
                                            case 'Alpha':
                                                $statusConfig = ['label' => 'ALPHA', 'class' => 'badge-soft-danger'];
                                                break;
                                            default:
                                                $statusConfig = ['label' => 'BELUM ABSEN', 'class' => 'badge-soft-secondary'];
                                                break;
                                        }
                                    @endphp

                                    <tr>
                                        <td class="text-center font-weight-bold text-muted px-4 font-size-13">{{ $loop->iteration }}</td>
                                        <td>
                                            <div class="font-weight-bold text-dark font-size-14">{{ $employee->name }}</div>
                                            <small class="text-muted text-uppercase" style="font-size: 0.7rem; letter-spacing: 0.5px;">NIP: {{ $employee->nip }}</small>
                                        </td>

                                        <td class="text-center">
                                            <span class="font-weight-bold font-size-14 {{ $timeIn != '-' ? 'text-success' : 'text-muted' }}"><i class="far fa-clock mr-1 small"></i> {{ $timeIn }}</span>
                                        </td>
                                        <td class="text-center">
                                            <span class="font-weight-bold font-size-14 {{ $timeOut != '-' ? 'text-primary' : 'text-muted' }}"><i class="far fa-clock mr-1 small"></i> {{ $timeOut }}</span>
                                        </td>
                                        <td class="text-center">
                                            <span class="badge {{ $statusConfig['class'] }} px-3 py-2 font-weight-600 shadow-none border-0" style="min-width: 90px;">
                                                {{ $statusConfig['label'] }}
                                            </span>
                                        </td>
                                        <td class="text-center px-4">
                                            <a href="{{ route('attendance.employeeHistory', $employee->nip) }}" class="btn btn-xs btn-outline-primary rounded-pill px-3 shadow-sm">
                                                <i class="fas fa-search mr-1"></i> Log
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@push('styles')
<style>
    /* Card & General */
    .calendar-sidebar { border-radius: 16px !important; }
    .main-card { border-radius: 16px !important; }
    .rounded-xl { border-radius: 12px; }
    .letter-spacing-1 { letter-spacing: 1px; }
    
    /* Stats Container */
    .stat-row:hover { background: #fff; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05); transform: translateX(5px); }
    .transition-all { transition: all 0.2s ease; }

    /* Custom Calendar Styling */
    .custom-calendar {
        background: #fff;
        border-radius: 12px;
    }
    .calendar-header h6 { color: #1e293b; font-size: 0.95rem; }
    .btn-icon-small {
        width: 30px; height: 30px; display: flex; align-items: center; justify-content: center;
        border-radius: 8px; color: #64748b; background: #f8fafc; border: none;
    }
    .btn-icon-small:hover { background: #f1f5f9; color: #3b82f6; }
    
    .calendar-weekdays { display: grid; grid-template-columns: repeat(7, 1fr); text-align: center; }
    .calendar-weekdays span { font-size: 0.65rem; font-weight: 700; color: #94a3b8; text-transform: uppercase; }
    
    .calendar-days { display: grid; grid-template-columns: repeat(7, 1fr); gap: 2px; }
    .calendar-day {
        aspect-ratio: 1; display: flex; align-items: center; justify-content: center;
        font-size: 0.75rem; font-weight: 600; border-radius: 6px; cursor: pointer;
        transition: all 0.2s; color: #475569; padding: 5px;
    }
    .calendar-day:hover:not(.empty):not(.active) { background: #f1f5f9; color: #3b82f6; }
    .calendar-day.active { background: #3b82f6; color: #fff; font-weight: 700; box-shadow: 0 4px 10px rgba(59, 130, 246, 0.3); }
    .calendar-day.today { color: #3b82f6; font-weight: 700; border: 1px dashed #3b82f6; }
    .calendar-day.empty { cursor: default; }

    /* Table & Badges */
    .badge-soft-success { background-color: #f0fdf4; color: #16a34a; border: 1px solid #bbf7d0; box-shadow: 0 1px 2px rgba(22, 163, 74, 0.05); }
    .badge-soft-warning { background-color: #fffbeb; color: #d97706; border: 1px solid #fde68a; box-shadow: 0 1px 2px rgba(217, 119, 6, 0.05); }
    .badge-soft-info { background-color: #f0f9ff; color: #0369a1; border: 1px solid #bae6fd; box-shadow: 0 1px 2px rgba(3, 105, 161, 0.05); }
    .badge-soft-danger { background-color: #fef2f2; color: #dc2626; border: 1px solid #fecaca; box-shadow: 0 1px 2px rgba(220, 38, 38, 0.05); }
    .badge-soft-secondary { background-color: #f9fafb; color: #4b5563; border: 1px solid #e5e7eb; box-shadow: 0 1px 2px rgba(75, 85, 99, 0.05); }
    
    .font-size-13 { font-size: 13px !important; }
    .font-size-14 { font-size: 14px !important; }
    .font-weight-500 { font-weight: 500 !important; }
    .font-weight-600 { font-weight: 600 !important; }
    .italic { font-style: italic; }
    
    .table tr { transition: all 0.2s ease; }
    .table tr:hover { background-color: rgba(59, 130, 246, 0.02) !important; transform: scale(1.002); }
    
    .card { transition: transform 0.3s ease, box-shadow 0.3s ease; }
    .card:hover { box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05) !important; }

    .btn-xs { padding: 0.25rem 0.5rem; font-size: 0.75rem; transition: all 0.2s; border-radius: 6px !important; }
    .btn-xs:hover { transform: translateY(-1px); }
    .sticky-top { transition: all 0.3s ease; }
</style>
@endpush

@push('scripts')
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const currentDateStr = "{{ $date }}";
        let [currentYear, currentMonth, currentDay] = currentDateStr.split('-').map(Number);
        
        const monthNames = ["Januari", "Februari", "Maret", "April", "Mei", "Juni", 
                          "Juli", "Agustus", "September", "Oktober", "November", "Desember"];

        const monthDisplay = document.getElementById('monthDisplay');
        const calendarDays = document.getElementById('calendarDays');
        const prevBtn = document.getElementById('prevMonth');
        const nextBtn = document.getElementById('nextMonth');

        // Initial view month based on URL date
        let viewMonth = currentMonth - 1;
        let viewYear = currentYear;

        function renderCalendar() {
            calendarDays.innerHTML = '';
            monthDisplay.textContent = `${monthNames[viewMonth]} ${viewYear}`;

            const firstDay = new Date(viewYear, viewMonth, 1).getDay();
            const daysInMonth = new Date(viewYear, viewMonth + 1, 0).getDate();

            // Fill empty slots for previous month
            for (let i = 0; i < firstDay; i++) {
                const emptyDiv = document.createElement('div');
                emptyDiv.classList.add('calendar-day', 'empty');
                calendarDays.appendChild(emptyDiv);
            }

            // Fill days
            const today = new Date();
            for (let i = 1; i <= daysInMonth; i++) {
                const dayDiv = document.createElement('div');
                dayDiv.classList.add('calendar-day');
                dayDiv.textContent = i;

                const dateStr = `${viewYear}-${String(viewMonth + 1).padStart(2, '0')}-${String(i).padStart(2, '0')}`;
                
                if (dateStr === currentDateStr) {
                    dayDiv.classList.add('active');
                }

                if (viewYear === today.getFullYear() && viewMonth === today.getMonth() && i === today.getDate()) {
                    dayDiv.classList.add('today');
                }

                dayDiv.onclick = () => window.location.href = `{{ route('attendance.monitoring') }}?date=${dateStr}`;
                calendarDays.appendChild(dayDiv);
            }
        }

        prevBtn.onclick = () => {
            viewMonth--;
            if (viewMonth < 0) {
                viewMonth = 11;
                viewYear--;
            }
            renderCalendar();
        };

        nextBtn.onclick = () => {
            viewMonth++;
            if (viewMonth > 11) {
                viewMonth = 0;
                viewYear++;
            }
            renderCalendar();
        };

        renderCalendar();
    });
</script>
@endpush
@endsection
